os: linux
sudo: required
language: node_js

node_js:
- "10"

cache: npm

install:
- npm ci

script:
- npm run lint

after_success:
- zip -r deploy.zip node_modules crawler.js index.js package.json package-lock.json
- rm -rf !("deploy.zip")

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: domain-combine-lambda
    region: ap-northeast-2
    skip_cleanup: true
    wait-until-deployed: true
    on:
      branch: master
