os: linux
sudo: required
language: node_js

node_js:
- "10"

cache: npm

install:
- npm ci

script:
- npm run lint

after_success:
- rm -rf node_modules
- npm i --only=prod

deploy:
  - provider: lambda
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    function_name: domain-combine-updater
    role: $LAMBDA_ROLE_ARN
    region: ap-northeast-2
    module_name: index
    handler_name: handler
    runtime: nodejs8.10
    memory_size: 1024
    timeout: 180
